# Generated by Django 4.2.5 on 2023-12-13 14:39 - modified to template order
from django.db import migrations


class Migration(migrations.Migration):
    initial = False

    dependencies = []
    operations = []
