version: '3.9'
services:
  {{ project_name }}_postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    restart: always
    volumes:
      - {{ project_name }}_postgres_data:/var/lib/postgresql/data
    env_file:
        - ../envs/develop.env
    container_name: {{ project_name }}_postgres
    command: postgres -c config_file=/opt/postgres/postgresql.conf
    ports:
      - "5432:5432"

volumes:
  {{ project_name }}_postgres_data:
    name: {{ project_name }}_postgres_data
