exclude: "^.*(migrations|fluent_comments|pyproject.toml).*$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        args:
          - --force-exclude='pyproject.toml'
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: flake8p
        language_version: python3
        additional_dependencies: [Flake8-pyproject]
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        args: [--tabwidth, "2"]
        files: ^.*\/templates\/.*.html.djt$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    - id: mypy
      entry: python -m mypy
      language: python
      args: [--no-warn-unused-ignores, --ignore-missing-imports]
      additional_dependencies: [
        django-stubs,
        djangorestframework-stubs,
        django-environ,
        django-cors-headers,
        msgspec,
        django-crispy-forms,
        crispy-tailwind,
        django-extensions,
        django-widget-tweaks,
        djangorestframework,
        djangorestframework-stubs,
        django-vite,
        django-debug-toolbar,
      ]
