# postgres: postgres -D databases/postgres
# web: PYTHONUNBUFFERED=true $WORKON_HOME/{{ project_name }}/bin/python manage.py runserver 0.0.0.0:8000 --settings=config.settings.develop
web: gunicorn {{project_name}}.config.wsgi:application
# notebook: DJANGO_ALLOW_ASYNC_UNSAFE=true DJANGO_SETTINGS_MODULE=config.settings.develop python manage.py shell_plus --notebook
