name: "BUG-to-issue"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "BUG to Issue"
        uses: "alstr/todo-to-issue-action@v2.1"
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "# BUG"
          COMMENT_MARKER: "#"
        id: "bug"
