"""
Django base settings for {{ project_name }}.

Generated by 'django-admin startproject' using {{ django_version }}.

For more information on this file, see
https://docs.djangoproject.com/en/{{ docs_version }}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/
"""
# Settings are imported here to make them available for django.conf.settings
# so, ignore linting errors for unused imports
# ruff: noqa: F401

# Stubs will monkeypatch django to provide type hints. See EOF for details.
import django_stubs_ext

# Providing access to the projects environment variables.
from ._environ import env  # noqa # pylint: disable=unused-import

# --- Explicitly importing all settings from submodules -----------------------
from .apps import INSTALLED_APPS  # noqa # pylint: disable=unused-import
from .databases import (
    DATABASES,  # noqa # pylint: disable=unused-import
    DEFAULT_AUTO_FIELD,  # noqa # pylint: disable=unused-import
    CACHES,  # noqa # pylint: disable=unused-import
)
from .gateway import WSGI_APPLICATION  # noqa # pylint: disable=unused-import
from .internationalization import (
    LANGUAGE_CODE,  # noqa # pylint: disable=unused-import
    TIME_ZONE,  # noqa # pylint: disable=unused-import
    USE_I18N,  # noqa # pylint: disable=unused-import
    USE_L10N,  # noqa # pylint: disable=unused-import
    USE_TZ  # noqa # pylint: disable=unused-import
)
from .logging import (
    LOG_DATABASE,   # noqa # pylint: disable=unused-import
    LOGGING_FILE_HANDLER,  # noqa # pylint: disable=unused-import
    LOGGING,  # noqa # pylint: disable=unused-import
)
from .middleware import MIDDLEWARE  # noqa # pylint: disable=unused-import
from .paths import (
    ROOT_DIR,  # noqa # pylint: disable=unused-import
    APPS_DIR,  # noqa # pylint: disable=unused-import
)
from .project import (
    VERSION,  # noqa # pylint: disable=unused-import
    PROJECT_TITLE,  # noqa # pylint: disable=unused-import
)
from .security import (
    DEBUG,  # noqa # pylint: disable=unused-import
    ALLOWED_HOSTS,  # noqa # pylint: disable=unused-import
    CORS_ALLOWED_ORIGINS,  # noqa # pylint: disable=unused-import
    CORS_ALLOW_HEADERS,  # noqa # pylint: disable=unused-import
    CORS_ALLOW_METHODS,  # noqa # pylint: disable=unused-import
    SECRET_KEY  # noqa # pylint: disable=unused-import
)
from .static import (
    STATIC_ROOT,  # noqa # pylint: disable=unused-import
    STATIC_HOST,  # noqa # pylint: disable=unused-import
    STATIC_URL,  # noqa # pylint: disable=unused-import
    STATICFILES_DIRS,  # noqa # pylint: disable=unused-import
    STATICFILES_FINDERS,  # noqa # pylint: disable=unused-import
    MEDIA_ROOT,  # noqa # pylint: disable=unused-import
    MEDIA_URL,  # noqa # pylint: disable=unused-import
)
from .templates import TEMPLATES  # noqa # pylint: disable=unused-import
from .urlconf import (
    ADMIN_URL,  # noqa # pylint: disable=unused-import
    LOGIN_REDIRECT_URL,  # noqa # pylint: disable=unused-import
    LOGOUT_REDIRECT_URL,  # noqa # pylint: disable=unused-import
    LOGIN_URL,  # noqa # pylint: disable=unused-import
    ROOT_URLCONF,  # noqa # pylint: disable=unused-import
    API_BASE_URL,  # noqa # pylint: disable=unused-import

)
from .users import (
    AUTH_USER_MODEL,  # noqa # pylint: disable=unused-import
    AUTH_PASSWORD_VALIDATORS,  # noqa # pylint: disable=unused-import
)

# -----------------------------------------------------------------------------

from .thirdparty import *  # noqa # pylint: disable=wildcard-import,unused-wildcard-import

# -----------------------------------------------------------------------------

# Monkeypatching Django, so stubs will work for all generics,
# see: https://github.com/typeddjango/django-stubs
django_stubs_ext.monkeypatch()
