version: '3.9'
services:
  {{ project_name }}_postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
        - ./envs/local.env
    container_name: {{ project_name }}_postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    name: {{ project_name }}_postgres_data
