---
name: build-templates
on:
  push:
    branches:
      - "trunk"
jobs:
  build-templates:
    name: "Build release Templates"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vimtor/action-zip@v1
        with:
          files: app_template_default/
          dest: app_template_default.zip
      - uses: vimtor/action-zip@v1
        with:
          files: app_template_rest/
          dest: app_template_rest.zip
      - uses: vimtor/action-zip@v1
        with:
          files: app_template_authentication/
          dest: app_template_authentication.zip
      - uses: vimtor/action-zip@v1
        with:
          files: app_template_simple_crud_templates/
          dest: app_template_simple_crud_templates.zip
      - uses: vimtor/action-zip@v1
        with:
          files: app_template_vuejs_templates/
          dest: app_template_vuejs_templates.zip
      - uses: vimtor/action-zip@v1
        with:
          files: project_template_django/
          dest: project_template_django.zip
      - uses: vimtor/action-zip@v1
        with:
          files: project_template_cli/
          dest: project_template_cli.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Template Build"
          files: |
            app_template_default.zip
            app_template_rest.zip
            app_template_authentication.zip
            app_template_simple_crud_templates.zip
            app_template_vuejs_templates.zip
            project_template.zip
