---
name: build-templates
on:
  push:
    branches:
      - "trunk"
jobs:
  build-templates:
    name: "Build release Templates"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vimtor/action-zip@v1
        with:
          files: app_template/
          dest: app_template.zip
      - uses: vimtor/action-zip@v1
        with:
          files: project_template/
          dest: project_template.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Template Build"
          files: |
            app_template.zip
            project_template.zip
